### ISSUE TITLE
有没有As版本的???AsProject是空Project???

### ISSUE THREAD

**Issue by lydlovezjr** [MobClub/MobLink-for-Android#1]
![TIM截图20190909215012](https://user-images.githubusercontent.com/19246347/64536579-ee910480-d34b-11e9-805c-4e5b2e7dbf8e.png)

**Comment by moblarry** [comment]
您下载周导入里面的两个Demo工程即可，无需管这个文件下的内容，这个是自动设置好的

**Comment by Larry1992Fei** [comment]
您下载周导入里面的两个Demo工程即可，无需管这个文件下的内容，这个是自动设置好的

**Comment by changmingyin** [comment]
老实说 真不会跑这个demo  请指导一下，下载下来 asproject里面没有东西

**Comment by BIGMONK** [comment]
新建/打开一个android studio 项目，file>new>Import Module  然后选择MobLink-DemoPro
